name: music_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.3.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  just_audio: ^0.9.38
  rxdart: ^0.27.7
  audio_video_progress_bar: ^2.0.2
  audioplayers: ^6.1.0
  youtube_explode_dart: ^2.2.0
  youtube_player_iframe: ^5.2.2
  firebase_core: ^3.5.0
  firebase_auth: ^5.4.1
  firebase_storage: ^12.3.0
  cloud_firestore: ^5.4.4
  provider: ^6.1.2
  file_picker: ^8.0.5
  uuid: ^4.4.0
  font_awesome_flutter: ^10.7.0
  lucide_icons: ^0.257.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/songs.json
    - assets/itunes_256.png
